backend:
    name: git-gateway
    branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "/public/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/uploads" # The src attribute for uploaded medi
logo_url: https://sestricna-bratic.netlify.app/cms.svg

# local_backend: true

collections:

    - name: "blog" # Used in routes, e.g., /admin/collections/blog
      label: "blog" # Used in the UI
      folder: "src/content/blog/" # The path to the folder where the documents are stored
      create: true # Allow users to create new documents in this collection
      slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
      fields: # The fields for each document, usually in front matter
          - {label: "Naslov", name: "title", widget: "string"}
          - {label: "Kratki Opis", name: "description", widget: "string"}
          - {label: "Publish Datum", name: "pubDate", widget: "datetime"}
          - {label: "Hero image", name: "heroImage", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"}
