backend:
    name: git-gateway
    branch: master
    repo: mrAtimed/sestricna-bratic

publish_mode: editorial_workflow

media_folder: "/public/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/uploads" # The src attribute for uploaded medi
logo_url: https://sestricna-bratic.netlify.app/cms.svg
local_backend: true


collections:

- name: "blog" 
  label: "Blogovi" # Used in the UI
  folder: "src/content/blog/" 
  create: true 
  slug: "{{slug}}"
  fields: 
      - {label: "Naslov", name: "title", widget: "string"}
      - {label: "Kratki Opis", name: "description", widget: "string"}
      - {label: "Publish Datum", name: "pubDate", widget: "datetime"}
      - {label: "Hero image", name: "heroImage", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
- name: "slider" 
  label: "Slider Početna" # Used in the UI
  folder: "src/content/slider/" 
  create: true 
  slug: "{{slug}}"
  fields: 
      - {label: "Sub", name: "sub", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Desc", name: "desc", widget: "string"}
      - {label: "Btn", name: "btn", widget: "string"}
      - {label: "Link", name: "link", widget: "string"}
- name: "usluge" 
  label: "Usluge Stranice" # Used in the UI
  folder: "src/content/services/" 
  create: true 
  slug: "{{slug}}"
  fields: 
      - {label: "Naslov", name: "title", widget: "string"}
      - {label: "Kratki Opis", name: "description", widget: "string"}
      - {label: "Publish Datum", name: "pubDate", widget: "datetime"}
      - {label: "image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
- name: "footer" 
  label: "Navigacija Footer" # Used in the UI
  folder: "src/content/footer/" 
  create: true 
  slug: "{{slug}}"
  fields: 
      - {label: "Naslov", name: "title", widget: "string"}
      - {label: "Kratki Opis", name: "description", widget: "string"}
      - {label: "Publish Datum", name: "pubDate", widget: "datetime"}
      - {label: "Hero image", name: "heroImage", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
